#!bin/bash

# https://texteditor.com/multiline-text-art/

echo -e "

                                              Welcome to

 o     _|_  _  __  _    _ _|_ o     _      __       _|  o  _     \  / o __       _   |  o __  _  __
 | |\|  |_ (/_ |  |_|_ |_  |_ | \/ (/_    |--| |_| (_|_ | [_]     \/  |  /_ |_| |_|_ |_ | _\ (/_ |



                                             This is where                                      🎶
                                             c                                        🎻
                                              o                                    🎷
                                                 l                         ♯♪
                                                     o                 ♮♭
                                                         r
                                               turns into   🎵
                                             [_  _     _  _|
                                             __](_)|_|| )(_|

                                                   and

                                               s
                                                 o
                                                    u
                                                       n
                                                          d
                          r
              u                     n
    t                                          s                                                .
                                                      i                             .
                                                              n               o
                                                                      t

                                                    /\\
                                            __  __  |/  __   _
                                           |__ |__| |  |__| |  \033[34;1;4m.\033[0m  \033[32;1;4m.\033[0m \033[31;1;4m.\033[0m 






                                               🔅 Enjoy! 😎

"
