name: Continuous Integration and Static Analysis for IAV
run-name: "🚀 IAV CI Build | Repo: ${GITHUB_REPOSITORY} | Status: ${{ github.action_status }} | Commit: ${{ github.sha }} 🛠️"
on: [push]
  branches:
      - refactor
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Install cppcheck and clang-tidy
        run: apt-get update && apt-get install -y cppcheck clang-tidy

      - name: Checkout code
      - uses: actions/checkout@v4

      - name: static analysis with cppcheck
        run: bash ${PWD}/scripts/gen_staticAnalysisLogs.sh

      - name: Build tests
        run: bash ${PWD}/scripts/compileTests.sh

      - name: Apply tests
        run: ${PWD}/test/build/test_all

      - name: Upload cppcheck and clang-tidy output as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: static-analysis-log-files
          path: |
            ${PWD}/checks/cppcheck.log
            ${PWD}/checks/clang-tidy.log